# Generated by Django 4.2.6 on 2023-12-27 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickerchartapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='volume',
            field=models.CharField(default='', max_length=255),
        ),
    ]
